
srp_raid_log:
  target: test
  outputs:
    test:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server' # (The ODBC Driver installed on your system)
      server: "sql-star-prod-001.database.windows.net"
      database: "sqldb-srp-import-prod-001"
      port: 1433
      schema: 'dbt_test' 
      user: mlSrpConnection
      password: "{{env_var('DBT_SQL_SECRET')}}"
      threads: 4
    prod:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server' # (The ODBC Driver installed on your system)
      server: "sql-star-prod-001.database.windows.net"
      database: "sqldb-srp-import-prod-001"
      port: 1433
      schema: 'prod' 
      user: mlSrpConnection
      password: "{{env_var('DBT_SQL_SECRET')}}"
      threads: 4
